config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root 'posts#index', as: :authenticated_user
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, skip: [:sessions]
  
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    post 'sign_in', to: 'devise/sessions#create', as: :user_session
    delete 'sign_out', to: 'devise/sessions#destroy'
    root 'devise/sessions#new'
  end
  
  get 'dashboard', to: 'users#dashboard'
  get 'notifications', to: 'notifications#show'

  resources :posts do
    resources :comments, skip: [:index, :new]
    resources :likes, only: [:new]
  end
  
  resources :friendships, only: [:new]
  put 'friendships/confirms_friend/:friend_id', to: 'friendships#update', as: :friendship_confirm

  get 'users', to: 'users#index'
  get 'users/:id', to: 'users#show', as: :user
  #resources :users, only: [:show]
  #get 'users/:id', to 'users#'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :text, presence: true
  validates :text, length: { maximum: 300 }
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[create]
  before_action :find_post

  def create
    @comment = @post.comments.build(comment_params)
    current_user.comments << @comment
    flash[:error] = @comment.errors.full_messages.to_sentence unless @comment.save
    redirect_to posts_path
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/_comment_form.html.erb
<div class="p-2">
  <h2 class="h5">Comment something :)</h2>
  <%= form_for(@comment, url: post_comments_path(object.id, @comment), html: { class: "w-100" }) do |f| %>
    <%= f.text_area :text, class: 'form-control', placeholder: "Write a comment..." %>
    <div class="d-flex justify-content-end py-2">
      <%= f.submit 'comment', class: "btn btn-primary px-4" %>
    </div>
  <% end %>
</div>

app/views/comments/_comments.html.erb
<% if !object.empty? %>
  <% object.each do |comment| %>
    <div class="m-2 pl-2 border border-radius"> 
      <p class="font-weight-bold pt-2"> 
        <%= comment.user.first_name %>
      </p>
      <p>
        <%= comment.text %>
      </p>
    </div>
  <% end %>
<% end %>