config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root 'posts#index', as: :authenticated_user
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, skip: [:sessions]
  
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    post 'sign_in', to: 'devise/sessions#create', as: :user_session
    delete 'sign_out', to: 'devise/sessions#destroy'
    root 'devise/sessions#new'
  end
  
  get 'dashboard', to: 'users#dashboard'
  get 'notifications', to: 'notifications#show'

  resources :posts do
    resources :comments, skip: [:index, :new]
    resources :likes, only: [:new]
  end
  
  resources :friendships, only: [:new]
  put 'friendships/confirms_friend/:friend_id', to: 'friendships#update', as: :friendship_confirm

  get 'users', to: 'users#index'
  get 'users/:id', to: 'users#show', as: :user
  #resources :users, only: [:show]
  #get 'users/:id', to 'users#'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]
  validates :first_name, :last_name, :email, presence: true
  validates :first_name, length: { minimum: 2 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email,
            length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_many :posts
  has_many :comments
  has_many :likes
  has_many :sent_friendships, class_name: 'Friendship', foreign_key: 'user_id'
  has_many :received_friendships, class_name: 'Friendship', foreign_key: 'friend_id'

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if (data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info'])
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def comments_post(post, text)
    comments.create!(
      post: post,
      text: text
    )
  end

  def likes_post(post)
    likes.create!(
      post: post
    )
  end

  def confirms_friendship(user)
    friendship = received_friendships.find do |item|
      item.user == user &&
        item.confirmed == false
    end
    friendship.confirmed = true
    friendship.save
    Friendship.create!(
      user: self,
      friend: user,
      confirmed: true,
      mirror: true
    )
  end

  def requests_friendship(receiver)
    friendship = sent_friendships.new(
      friend: receiver
    )
    if friendship.valid?
      friendship.save
    else
      errors.add(:not_to_itself, friendship.errors.messages[:not_to_itself])
      errors.add(:already_received, friendship.errors.messages[:already_received])
      errors.add(:already_sent, friendship.errors.messages[:already_sent])
      errors.add(:already_friends, friendship.errors.messages[:already_friends])
      false
    end
  end

  def friend?(user)
    friends.include?(user)
  end

  def friends
    friends_array = sent_friendships.map do |friendship|
      friendship.friend if friendship.confirmed && (friendship.mirror == false)
    end
    friends_array += received_friendships.map do |friendship|
      friendship.user if friendship.confirmed && (friendship.mirror == false)
    end
    friends_array.compact
  end

  def requests_sent
    sent_friendships.map { |friendship| friendship.friend unless friendship.confirmed }.compact
  end

  def requests_received
    received_friendships.map { |friendship| friendship.user unless friendship.confirmed }.compact
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[show index]

  def dashboard
    timeline_posts
    @comment = Comment.new
  end

  def index
    @friends = current_user.friends
    @sender_users = current_user.requests_received
    @receiver_users = current_user.requests_sent
    @rest_of_users = User.all - @friends - @sender_users - @receiver_users

    @unconfirmed_sent_friendships = current_user.requests_sent
    @requests_received = current_user.requests_received
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def friendship_requested_pending?(friend)
    @unconfirmed_sent_friendships.include?(friend)
    # return confirm friendship, pending or request friendship, also Friends as a text
  end

  def friendship_unconfirmed?(friend)
    @requests_received.include?(friend)
  end
end

app/views/users/_friends.html.erb
<% object[:users].each do |u| %>
  <ul class="list-unstyled">
    <% if u != current_user%>
      <li>
        <div class="row border-bottom pb-3">
          <div class="col-3 d-flex align-items-center">
            <%= link_to "@" + u.first_name + " " + u.last_name, "users/" + u.id.to_s %>
          </div>
          <div class="col-3">
            <% if friendship_requested_pending?(u) %>
              <div class="btn btn-warning btn-small w-100">Pending</div>
            <% elsif friendship_unconfirmed?(u) %>
              <%= link_to "Confirm Friendship", friendship_confirm_path(u), class: 'btn btn-success btn-small w-100', method: :put %>
            <% elsif current_user.friend?(u) %>
              <div class="btn btn-success btn-small w-100">Friends</div>
            <% else %>
              <%= link_to "Send Friendship Request", new_friendship_path(user: u), class: 'btn btn-primary btn-small w-100' %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/users/dashboard.html.erb
<section>
  <h2 class="h5">My posts</h2>
  <%= render 'posts/posts_list' %>
</section>

app/views/users/index.html.erb
<section>
  <h2 class="h4">Friends</h2>
  <%= render 'friends', object: {users: @friends} unless @friends.empty? %> 
  <h2 class="h4">Users you have sent a request to</h2>  
  <%= render 'friends', object: {users: @receiver_users} unless @receiver_users.empty? %> 
  <h2 class="h4">Users you have received a request from</h2>
  <%= render 'friends', object: {users: @sender_users} unless @sender_users.empty? %> 
  <h2 class="h4">Rest of the users</h2>
  <%= render 'friends', object: {users: @rest_of_users} unless @rest_of_users.empty? %> 
</section>

app/views/users/show.html.erb
<section class="p-2">
  <h1>User Data</h1>
  <p>First Name: <%= @user.first_name%></p>
  <p>Last Name: <%= @user.last_name%></p>
  <p>E-mail:<%= @user.email%></p>
  <p>Id: <%= @user.id %></p>
  <%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-primary' %>
</section>