config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root 'posts#index', as: :authenticated_user
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, skip: [:sessions]
  
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    post 'sign_in', to: 'devise/sessions#create', as: :user_session
    delete 'sign_out', to: 'devise/sessions#destroy'
    root 'devise/sessions#new'
  end
  
  get 'dashboard', to: 'users#dashboard'
  get 'notifications', to: 'notifications#show'

  resources :posts do
    resources :comments, skip: [:index, :new]
    resources :likes, only: [:new]
  end
  
  resources :friendships, only: [:new]
  put 'friendships/confirms_friend/:friend_id', to: 'friendships#update', as: :friendship_confirm

  get 'users', to: 'users#index'
  get 'users/:id', to: 'users#show', as: :user
  #resources :users, only: [:show]
  #get 'users/:id', to 'users#'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
  validates :text, :user_id, presence: true
  validates :text, length: { in: 5..300 }

  scope :recent_posts, -> { order(created_at: :desc) }
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create destroy]

  def index
    timeline_posts
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy; end

  private

  def post_params
    params.require(:post).permit(:text)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_post.html.erb
<% object.each do |post| %>
  <article class="p-2 border rounded mb-3">
    <p class="m-0 pl-2 pr-0">Author: <%= post.user.first_name %> shared a post</p>
    <p class="small pl-2 pr-0"><%= post.created_at.to_date %> at <%= post.created_at.hour %>:<%= post.created_at.min %></p>
    <p class="pl-2 pr-0"><%= post.text %></p>
    <%= render 'comments/comments', object: post.comments %>
    <%= render 'comments/comment_form', object: post %>  
    <%= link_to "Like", new_post_like_path(post) %> <span><%= post.likes.count %></span>
    <%= link_to "Comment", "#"%> 
  </article>
<% end %>

app/views/posts/_posts_list.html.erb
<% if !@friends.empty? %>
  <% @friends.each do |friend| %>
    <% if !friend.posts.recent_posts.empty? %>
      <%= render 'posts/post', object: friend.posts.recent_posts %>
    <% end %>
  <% end %>
<% end %>
<% if !@posts.empty? %>
  <%= render 'posts/post', object: @posts %>
<% else %>
  <div>
    <span>There aren't posts to show</span>
  </div> 
<% end %>

app/views/posts/index.html.erb
<section>
  <h2 class="h3">Share something <span class="text-dark"><%= current_user.first_name %></span></h2>
  <h2 class="h4">All posts</h2>
  <%= render 'posts/posts_list' %>
</section>

app/views/posts/new.html.erb
<div class="p-2">
  <h2 class="h5">Create post</h2> <em>5 characters minimum</em>
  <%= form_for(@post, url: posts_url, html: { class: "w-100" }) do |f| %>
    <%= f.text_area :text, class: 'form-control', placeholder: "What are you thinking, #{current_user.first_name} ?" %>
    <div class="d-flex justify-content-end py-2">
      <%= f.submit 'post', class: "btn btn-primary px-4" %>
    </div>
  <% end %>
</div>