config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root 'posts#index', as: :authenticated_user
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, skip: [:sessions]
  
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    post 'sign_in', to: 'devise/sessions#create', as: :user_session
    delete 'sign_out', to: 'devise/sessions#destroy'
    root 'devise/sessions#new'
  end
  
  get 'dashboard', to: 'users#dashboard'
  get 'notifications', to: 'notifications#show'

  resources :posts do
    resources :comments, skip: [:index, :new]
    resources :likes, only: [:new]
  end
  
  resources :friendships, only: [:new]
  put 'friendships/confirms_friend/:friend_id', to: 'friendships#update', as: :friendship_confirm

  get 'users', to: 'users#index'
  get 'users/:id', to: 'users#show', as: :user
  #resources :users, only: [:show]
  #get 'users/:id', to 'users#'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<h5 class="my-0 mr-md-auto font-weight-normal">
  <%= link_to "Fakebook", root_url, id: "logo" %>
</h5>
<nav class="my-2 my-md-0 mr-md-3">
    <%if user_signed_in? %>
    <%= link_to "Users", users_path, class: "p-2 text-dark" %>
    <%= link_to "Notifications (#{ friend_requests_count().to_s })", notifications_path, class: 'p-2 text-dark' %>
    <%= link_to "Dashboard", dashboard_path, class: "p-2 text-dark" %>
    <%= link_to "Create Post", new_post_path, class: "p-2 text-dark" %>
    <%= link_to "Profile", current_user, class: "p-2 text-dark" %>
    <%= link_to "Log out", sign_out_path, class: "btn btn-outline-secondary p-2 text-dark", id: "logout", method: :delete %>
    <% else %>
    <%= link_to "Log in", new_user_session_path, class: "p-2 text-dark" %>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-primary" %>
    <% end %>   
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    <header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <%= render 'layouts/header' %>
    </header>
    <main  role="main" class="container h-150">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %> p-0"><%= message %></div>
        <% end %>
      <%= yield %>
    </main>
  </body>
</html>